# Generated by Django 4.2.4 on 2023-08-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='pats_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
