# Generated by Django 4.2.4 on 2023-08-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_rename_price_house_price_per_night'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='pats_allowed',
            new_name='pets_allowed',
        ),
    ]
