# Generated by Django 4.2.4 on 2023-08-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_alter_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
